services:
  - type: web
    name: anticam-bot
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TOKEN
        sync: false
      - key: DATABASE_URL
        value: sqlite:///bot_database.db
    plan: free
    autoDeploy: true